name: dart_counter
description: Dart Zähler mit Kameraerkennung
publish_to: none
version: 0.1.0
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0
  image: ^4.2.0
  shared_preferences: ^2.2.0
  audioplayers: ^6.1.0
flutter:
  uses-material-design: true
  assets:
    - assets/win.mp3